# Generated by Django 3.2.7 on 2021-09-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'blank': 'Username cannot be blank', 'unique': 'A user with that username already exists.'}, max_length=20, unique=True)),
                ('password', models.CharField(max_length=20, verbose_name='password')),
            ],
        ),
    ]
