# Generated by Django 3.2.7 on 2021-09-18 04:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='username',
            field=models.CharField(error_messages={'blank': 'Username cannot be blank', 'unique': 'A user with that username already exists.'}, max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
    ]
